nodeLinker: pnp

pnpEnableInlining: true

pnpFallbackMode: all

packageExtensions:
    "@preact/preset-vite@*":
        peerDependencies:
            "preact": "*"
    "vite-prerender-plugin@*":
        peerDependencies:
            "vite": "*"
